spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/bd_munoz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=conexión
spring.datasource.password=Wk2!rT8s@6w
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true